version: "3.3"
services:
  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
    networks:
      - docker-network
  ghost:
    image: ghost:5.22
    restart: always
    ports:
      - "2368:2368"
    depends_on:
      - db
    environment:
      url: https://www.bdsnhapho.site
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ghostdbpass
      database__connection__database: ghostdb
      mail__transport: SMTP
      mail__from: "'BDS Nhapho' <linhvan118319@gmail.com>"
      mail__options__host: email-smtp.ap-southeast-1.amazonaws.com
      mail__options__port: 465
      mail__options__service: SES
      mail__options__auth__user: ***
      mail__options__auth__pass: ***
    volumes:
      - content:/var/lib/ghost/content
    networks:
      - docker-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ghostdbpass
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostdbpass
      MYSQL_DATABASE: ghostdb
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - docker-network

volumes:
  mysql:
  content:
  caddy-data:
networks:
  docker-network:
    driver: bridge
